dat <- read.table("household_power_consumption.txt", header=T, sep=";", na.strings="?")
data <- dat[dat$Date %in% c("1/2/2007","2/2/2007"),]
time <-strptime(paste(data$Date, data$Time, sep=" "),"%d/%m/%Y %H:%M:%S")
data <- cbind(time, data)

labels <- c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
columns <- c("black","red","blue")
par(mfrow=c(2,2), mar = c(3, 4, 1, 1))
plot(data$time, data$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(data$time, data$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(data$time, data$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(data$time, data$Sub_metering_2, type="l", col="red")
lines(data$time, data$Sub_metering_3, type="l", col="blue")
legend("topright", bty="n", legend=labels, lty=1, col=columns)
plot(data$time, data$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")